create database tshirt_database;
use tshirt_database;
create table tshirt_Table (
shirt_Id int not null auto_increment primary key,
article_Type varchar (50) not null,
color varchar (100) not null, 
shirt_Size varchar (4),
last_Worn smallint
);
desc tshirt_Table;
alter table tshirt_Table modify shirt_Size varchar (6);
select * from tshirt_Table;
insert into tshirt_Table (shirt_Id, article_Type, color, shirt_Size, last_Worn)
values
(NULL, 'T-Shirt', 'Black', 'M', 5),
(NULL, 'T-Shirt', 'White', 'L', 10),
(NULL, 'T-Shirt', 'Navy Blue', 'XL', 1),
(NULL, 'Hoodie', 'Gray', 'S', 20),
(NULL, 'Polo Shirt', 'Red', 'M', 3),
(NULL, 'T-Shirt', 'Black', 'XS', 7),
(NULL, 'T-Shirt', 'White', 'XXL', 15),
(NULL, 'Tank Top', 'Yellow', 'S', 2),
(NULL, 'Sweatshirt', 'Green', 'L', 25),
(NULL, 'T-Shirt', 'Black', 'M', 1),
(NULL, 'Polo Shirt', 'White', 'XL', 4),
(NULL, 'T-Shirt', 'Red', 'XS', 6),
(NULL, 'Hoodie', 'Navy Blue', 'L', 30),
(NULL, 'Tank Top', 'Black', 'M', 9),
(NULL, 'T-Shirt', 'Gray', 'XXL', 12),
(NULL, 'T-Shirt', 'Green', 'S', 8),
(NULL, 'Polo Shirt', 'Black', 'XL', 18),
(NULL, 'T-Shirt', 'White', 'M', 2),
(NULL, 'Sweatshirt', 'Black', 'L', 35),
(NULL, 'T-Shirt', 'Yellow', 'XS', 11),
(NULL, 'T-Shirt', 'Red', 'XXL', 14),
(NULL, 'Tank Top', 'White', 'S', 5),
(NULL, 'Polo Shirt', 'Green', 'M', 1),
(NULL, 'T-Shirt', 'Navy Blue', 'L', 22),
(NULL, 'Hoodie', 'Red', 'XL', 17),
(NULL, 'T-Shirt', 'Black', 'S', 3),
(NULL, 'Polo Shirt', 'Gray', 'M', 16),
(NULL, 'T-Shirt', 'White', 'XS', 28),
(NULL, 'Sweatshirt', 'Navy Blue', 'XXL', 40),
(NULL, 'T-Shirt', 'Black', 'L', 13),
(NULL, 'Tank Top', 'Yellow', 'M', 7),
(NULL, 'Polo Shirt', 'Red', 'S', 19),
(NULL, 'T-Shirt', 'White', 'XL', 4),
(NULL, 'T-Shirt', 'Green', 'XS', 21),
(NULL, 'Hoodie', 'Black', 'M', 23),
(NULL, 'Polo Shirt', 'Navy Blue', 'L', 1),
(NULL, 'T-Shirt', 'Red', 'XXL', 2),
(NULL, 'Tank Top', 'Gray', 'XL', 10),
(NULL, 'Sweatshirt', 'White', 'S', 8),
(NULL, 'T-Shirt', 'Black', 'M', 14),
(NULL, 'T-Shirt', 'Navy Blue', 'XS', 26),
(NULL, 'Polo Shirt', 'Green', 'L', 3),
(NULL, 'T-Shirt', 'Yellow', 'XL', 11),
(NULL, 'Hoodie', 'Red', 'M', 5),
(NULL, 'T-Shirt', 'White', 'S', 17),
(NULL, 'Tank Top', 'Black', 'L', 29),
(NULL, 'Polo Shirt', 'White', 'XXL', 6),
(NULL, 'T-Shirt', 'Gray', 'M', 31),
(NULL, 'Sweatshirt', 'Yellow', 'XS', 2),
(NULL, 'T-Shirt', 'Green', 'XL', 15),
(NULL, 'Polo Shirt', 'Black', 'S', 9),
(NULL, 'T-Shirt', 'Red', 'L', 1),
(NULL, 'Hoodie', 'White', 'M', 27),
(NULL, 'Tank Top', 'Navy Blue', 'XXL', 4),
(NULL, 'T-Shirt', 'Black', 'XS', 18),
(NULL, 'Polo Shirt', 'Red', 'L', 7),
(NULL, 'T-Shirt', 'Yellow', 'M', 22),
(NULL, 'Sweatshirt', 'Green', 'XL', 33),
(NULL, 'T-Shirt', 'White', 'S', 10),
(NULL, 'Hoodie', 'Gray', 'L', 13),
(NULL, 'T-Shirt', 'Black', 'XXL', 1),
(NULL, 'Polo Shirt', 'Navy Blue', 'M', 24),
(NULL, 'Tank Top', 'Red', 'XS', 5),
(NULL, 'T-Shirt', 'Green', 'XL', 36),
(NULL, 'Sweatshirt', 'Black', 'S', 16),
(NULL, 'T-Shirt', 'Yellow', 'L', 8),
(NULL, 'Polo Shirt', 'White', 'M', 19),
(NULL, 'T-Shirt', 'Navy Blue', 'XXL', 3),
(NULL, 'Hoodie', 'Black', 'XS', 21),
(NULL, 'Tank Top', 'Green', 'L', 14),
(NULL, 'T-Shirt', 'Red', 'M', 28),
(NULL, 'Polo Shirt', 'Gray', 'XL', 2),
(NULL, 'T-Shirt', 'White', 'S', 39),
(NULL, 'Sweatshirt', 'Red', 'L', 12),
(NULL, 'T-Shirt', 'Black', 'M', 6),
(NULL, 'Tank Top', 'Yellow', 'XS', 20),
(NULL, 'Polo Shirt', 'Black', 'XL', 1),
(NULL, 'T-Shirt', 'Green', 'XXL', 25),
(NULL, 'Hoodie', 'Navy Blue', 'M', 9),
(NULL, 'T-Shirt', 'Red', 'S', 17),
(NULL, 'Polo Shirt', 'White', 'L', 4),
(NULL, 'T-Shirt', 'Black', 'XL', 30),
(NULL, 'Sweatshirt', 'Gray', 'M', 11),
(NULL, 'Tank Top', 'Red', 'XS', 33),
(NULL, 'T-Shirt', 'White', 'L', 7),
(NULL, 'Polo Shirt', 'Yellow', 'XXL', 15),
(NULL, 'T-Shirt', 'Navy Blue', 'S', 2),
(NULL, 'Hoodie', 'Green', 'M', 18),
(NULL, 'T-Shirt', 'Black', 'XL', 29),
(NULL, 'Polo Shirt', 'Red', 'L', 3),
(NULL, 'Sweatshirt', 'White', 'XS', 35),
(NULL, 'T-Shirt', 'Yellow', 'M', 10),
(NULL, 'Tank Top', 'Navy Blue', 'XXL', 24),
(NULL, 'T-Shirt', 'Red', 'S', 5),
(NULL, 'Polo Shirt', 'Black', 'XL', 19),
(NULL, 'T-Shirt', 'Green', 'L', 1),
(NULL, 'Hoodie', 'Gray', 'M', 37),
(NULL, 'Sweatshirt', 'Red', 'XS', 16),
(NULL, 'T-Shirt', 'Black', 'XXL', 8),
(NULL, 'Polo Shirt', 'Yellow', 'L', 4),
(NULL, 'Tank Top', 'White', 'M', 23),
(NULL, 'T-Shirt', 'Navy Blue', 'S', 12),
(NULL, 'Hoodie', 'Black', 'XL', 2),
(NULL, 'T-Shirt', 'White', 'L', 20),
(NULL, 'Polo Shirt', 'Green', 'M', 7),
(NULL, 'Sweatshirt', 'Navy Blue', 'XXL', 31),
(NULL, 'T-Shirt', 'Red', 'XS', 14),
(NULL, 'Tank Top', 'Black', 'XL', 9),
(NULL, 'T-Shirt', 'Yellow', 'S', 1),
(NULL, 'Polo Shirt', 'Red', 'L', 26),
(NULL, 'T-Shirt', 'Green', 'M', 34),
(NULL, 'Hoodie', 'White', 'XXL', 3),
(NULL, 'T-Shirt', 'Black', 'XS', 11),
(NULL, 'Sweatshirt', 'Yellow', 'L', 5),
(NULL, 'Polo Shirt', 'Black', 'M', 28),
(NULL, 'Tank Top', 'Red', 'XL', 17),
(NULL, 'T-Shirt', 'White', 'S', 4),
(NULL, 'Hoodie', 'Navy Blue', 'L', 32),
(NULL, 'T-Shirt', 'Red', 'XXL', 6),
(NULL, 'Polo Shirt', 'Green', 'M', 25),
(NULL, 'Sweatshirt', 'Black', 'XS', 10),
(NULL, 'T-Shirt', 'Yellow', 'L', 1),
(NULL, 'Tank Top', 'White', 'XL', 22),
(NULL, 'T-Shirt', 'Navy Blue', 'S', 13),
(NULL, 'Polo Shirt', 'Red', 'M', 29),
(NULL, 'Hoodie', 'Gray', 'XXL', 7),
(NULL, 'T-Shirt', 'Green', 'L', 36),
(NULL, 'Sweatshirt', 'White', 'XL', 15),
(NULL, 'T-Shirt', 'Black', 'S', 2),
(NULL, 'Tank Top', 'Yellow', 'M', 30),
(NULL, 'Polo Shirt', 'Navy Blue', 'XS', 8),
(NULL, 'T-Shirt', 'Red', 'L', 24),
(NULL, 'Hoodie', 'Black', 'XL', 19),
(NULL, 'T-Shirt', 'White', 'XXL', 5),
(NULL, 'Sweatshirt', 'Green', 'M', 38),
(NULL, 'Polo Shirt', 'Black', 'S', 11),
(NULL, 'Tank Top', 'Gray', 'L', 4),
(NULL, 'T-Shirt', 'Yellow', 'XL', 26),
(NULL, 'Hoodie', 'Red', 'M', 1),
(NULL, 'T-Shirt', 'Navy Blue', 'XS', 33),
(NULL, 'Polo Shirt', 'White', 'L', 10),
(NULL, 'Sweatshirt', 'Black', 'XXL', 21),
(NULL, 'T-Shirt', 'Red', 'M', 6),
(NULL, 'Tank Top', 'Green', 'S', 27),
(NULL, 'Polo Shirt', 'Red', 'XL', 3),
(NULL, 'T-Shirt', 'Black', 'L', 35),
(NULL, 'Hoodie', 'White', 'M', 14),
(NULL, 'T-Shirt', 'Green', 'XS', 22),
(NULL, 'Sweatshirt', 'Navy Blue', 'L', 9),
(NULL, 'Tank Top', 'Yellow', 'XXL', 1),
(NULL, 'T-Shirt', 'White', 'M', 30),
(NULL, 'Polo Shirt', 'Gray', 'S', 16),
(NULL, 'Hoodie', 'Red', 'XL', 5),
(NULL, 'T-Shirt', 'Black', 'L', 28),
(NULL, 'Sweatshirt', 'Yellow', 'M', 12),
(NULL, 'Tank Top', 'Black', 'XS', 2),
(NULL, 'Polo Shirt', 'Navy Blue', 'XXL', 39),
(NULL, 'T-Shirt', 'Red', 'S', 7),
(NULL, 'Hoodie', 'Green', 'L', 23),
(NULL, 'T-Shirt', 'White', 'XL', 18),
(NULL, 'Sweatshirt', 'Red', 'M', 4),
(NULL, 'Tank Top', 'Navy Blue', 'S', 34),
(NULL, 'Polo Shirt', 'Black', 'L', 11),
(NULL, 'T-Shirt', 'Yellow', 'XXL', 20),
(NULL, 'Hoodie', 'Gray', 'M', 1),
(NULL, 'T-Shirt', 'Navy Blue', 'XS', 37),
(NULL, 'Sweatshirt', 'White', 'L', 15),
(NULL, 'Tank Top', 'Red', 'XL', 6),
(NULL, 'Polo Shirt', 'Yellow', 'S', 29),
(NULL, 'T-Shirt', 'Black', 'M', 3),
(NULL, 'Hoodie', 'White', 'XXL', 26),
(NULL, 'T-Shirt', 'Green', 'L', 10),
(NULL, 'Sweatshirt', 'Navy Blue', 'XS', 24),
(NULL, 'Tank Top', 'Black', 'M', 5),
(NULL, 'Polo Shirt', 'Green', 'XL', 17),
(NULL, 'T-Shirt', 'Red', 'S', 28),
(NULL, 'Hoodie', 'Black', 'L', 13),
(NULL, 'T-Shirt', 'Yellow', 'XXL', 2),
(NULL, 'Sweatshirt', 'Gray', 'M', 31),
(NULL, 'Tank Top', 'Red', 'XS', 8),
(NULL, 'Polo Shirt', 'White', 'L', 19),
(NULL, 'T-Shirt', 'Navy Blue', 'XL', 4),
(NULL, 'Hoodie', 'Red', 'S', 33),
(NULL, 'T-Shirt', 'Black', 'M', 16),
(NULL, 'Sweatshirt', 'Yellow', 'XXL', 1),
(NULL, 'Tank Top', 'White', 'L', 25),
(NULL, 'Polo Shirt', 'Black', 'XS', 9),
(NULL, 'T-Shirt', 'Green', 'XL', 37),
(NULL, 'Hoodie', 'Navy Blue', 'M', 6),
(NULL, 'T-Shirt', 'Red', 'L', 20),
(NULL, 'Sweatshirt', 'White', 'S', 35),
(NULL, 'Tank Top', 'Yellow', 'XXL', 12),
(NULL, 'Polo Shirt', 'Red', 'M', 27),
(NULL, 'T-Shirt', 'Black', 'XL', 3),
(NULL, 'Hoodie', 'Green', 'L', 24),
(NULL, 'T-Shirt', 'White', 'XS', 10),
(NULL, 'Sweatshirt', 'Black', 'M', 29),
(NULL, 'Tank Top', 'Gray', 'XL', 7),
(NULL, 'Polo Shirt', 'Navy Blue', 'S', 32),
(NULL, 'T-Shirt', 'Red', 'L', 1),
(NULL, 'Hoodie', 'White', 'XXL', 15),
(NULL, 'T-Shirt', 'Yellow', 'M', 6),
(NULL, 'Sweatshirt', 'Red', 'XS', 28),
(NULL, 'Tank Top', 'Black', 'L', 4),
(NULL, 'Polo Shirt', 'Green', 'XL', 18),
(NULL, 'T-Shirt', 'Navy Blue', 'S', 36),
(NULL, 'Hoodie', 'Gray', 'M', 9),
(NULL, 'T-Shirt', 'White', 'XXL', 2),
(NULL, 'Sweatshirt', 'Yellow', 'L', 33),
(NULL, 'Tank Top', 'Red', 'XS', 11),
(NULL, 'Polo Shirt', 'Black', 'M', 25),
(NULL, 'T-Shirt', 'Green', 'XL', 8),
(NULL, 'Hoodie', 'Black', 'S', 19),
(NULL, 'T-Shirt', 'Red', 'L', 5),
(NULL, 'Sweatshirt', 'Navy Blue', 'M', 30),
(NULL, 'Tank Top', 'White', 'XXL', 1),
(NULL, 'Polo Shirt', 'Red', 'XS', 23),
(NULL, 'T-Shirt', 'Yellow', 'L', 14),
(NULL, 'Hoodie', 'White', 'XL', 27),
(NULL, 'T-Shirt', 'Black', 'S', 3),
(NULL, 'Sweatshirt', 'Gray', 'M', 39),
(NULL, 'Tank Top', 'Navy Blue', 'L', 16),
(NULL, 'Polo Shirt', 'Yellow', 'XXL', 10),
(NULL, 'T-Shirt', 'Red', 'XS', 29),
(NULL, 'Hoodie', 'Green', 'XL', 7),
(NULL, 'T-Shirt', 'White', 'M', 32),
(NULL, 'Sweatshirt', 'Red', 'L', 13),
(NULL, 'Tank Top', 'Black', 'S', 25),
(NULL, 'Polo Shirt', 'Navy Blue', 'XL', 2),
(NULL, 'T-Shirt', 'Yellow', 'XXL', 38),
(NULL, 'Hoodie', 'Red', 'M', 11),
(NULL, 'T-Shirt', 'Black', 'L', 5),
(NULL, 'Sweatshirt', 'White', 'XS', 34),
(NULL, 'Tank Top', 'Green', 'M', 17),
(NULL, 'Polo Shirt', 'Black', 'L', 26),
(NULL, 'T-Shirt', 'Navy Blue', 'XL', 1),
(NULL, 'Hoodie', 'Gray', 'S', 23),
(NULL, 'T-Shirt', 'White', 'M', 19),
(NULL, 'Sweatshirt', 'Black', 'XXL', 30),
(NULL, 'Tank Top', 'Yellow', 'L', 6),
(NULL, 'Polo Shirt', 'White', 'XL', 12),
(NULL, 'T-Shirt', 'Red', 'S', 37),
(NULL, 'Hoodie', 'Black', 'M', 8),
(NULL, 'T-Shirt', 'Green', 'XXL', 4),
(NULL, 'Sweatshirt', 'Navy Blue', 'L', 31),
(NULL, 'Tank Top', 'Red', 'XS', 15),
(NULL, 'Polo Shirt', 'Green', 'M', 2),
(NULL, 'T-Shirt', 'Black', 'XL', 28),
(NULL, 'Hoodie', 'White', 'L', 10),
(NULL, 'T-Shirt', 'Yellow', 'S', 35),
(NULL, 'Sweatshirt', 'Red', 'M', 7),
(NULL, 'Tank Top', 'Navy Blue', 'XXL', 1),
(NULL, 'Polo Shirt', 'Black', 'L', 24),
(NULL, 'T-Shirt', 'White', 'XS', 19),
(NULL, 'Hoodie', 'Gray', 'XL', 5),
(NULL, 'T-Shirt', 'Green', 'M', 33),
(NULL, 'Sweatshirt', 'Yellow', 'L', 14),
(NULL, 'Tank Top', 'Black', 'S', 26),
(NULL, 'Polo Shirt', 'White', 'XXL', 3),
(NULL, 'T-Shirt', 'Red', 'XL', 30),
(NULL, 'Hoodie', 'Navy Blue', 'M', 9),
(NULL, 'T-Shirt', 'Black', 'L', 17),
(NULL, 'Sweatshirt', 'White', 'XS', 36),
(NULL, 'Tank Top', 'Green', 'M', 4),
(NULL, 'Polo Shirt', 'Red', 'S', 22),
(NULL, 'T-Shirt', 'Yellow', 'L', 11),
(NULL, 'Hoodie', 'Black', 'XL', 29),
(NULL, 'T-Shirt', 'White', 'XXL', 8),
(NULL, 'Sweatshirt', 'Green', 'M', 34),
(NULL, 'Tank Top', 'Yellow', 'XS', 1),
(NULL, 'Polo Shirt', 'Black', 'L', 20),
(NULL, 'T-Shirt', 'Red', 'XL', 13),
(NULL, 'Hoodie', 'White', 'S', 27),
(NULL, 'T-Shirt', 'Navy Blue', 'M', 6),
(NULL, 'Sweatshirt', 'Gray', 'XXL', 31),
(NULL, 'Tank Top', 'Red', 'L', 18),
(NULL, 'Polo Shirt', 'Yellow', 'M', 25),
(NULL, 'T-Shirt', 'Black', 'XS', 2),
(NULL, 'Hoodie', 'Navy Blue', 'XL', 38),
(NULL, 'T-Shirt', 'Green', 'L', 15),
(NULL, 'Sweatshirt', 'Red', 'S', 28),
(NULL, 'Tank Top', 'Black', 'M', 5),
(NULL, 'Polo Shirt', 'Navy Blue', 'XXL', 12),
(NULL, 'T-Shirt', 'White', 'L', 3),
(NULL, 'Hoodie', 'Green', 'M', 36),
(NULL, 'T-Shirt', 'Red', 'XS', 10),
(NULL, 'Sweatshirt', 'Black', 'XL', 24),
(NULL, 'Tank Top', 'Yellow', 'S', 7),
(NULL, 'Polo Shirt', 'White', 'L', 33),
(NULL, 'T-Shirt', 'Navy Blue', 'M', 1),
(NULL, 'Hoodie', 'Red', 'XXL', 29),
(NULL, 'T-Shirt', 'Black', 'XL', 16),
(NULL, 'Sweatshirt', 'Gray', 'S', 4),
(NULL, 'Tank Top', 'White', 'M', 20),
(NULL, 'Polo Shirt', 'Yellow', 'L', 11),
(NULL, 'T-Shirt', 'Green', 'XS', 37),
(NULL, 'Hoodie', 'Black', 'XXL', 8),
(NULL, 'T-Shirt', 'Red', 'XL', 2),
(NULL, 'Sweatshirt', 'Navy Blue', 'M', 35),
(NULL, 'Tank Top', 'Red', 'L', 19),
(NULL, 'Polo Shirt', 'Green', 'S', 26),
(NULL, 'T-Shirt', 'White', 'XXL', 13),
(NULL, 'Hoodie', 'Gray', 'XL', 5),
(NULL, 'T-Shirt', 'Black', 'M', 30),
(NULL, 'Sweatshirt', 'Red', 'L', 9),
(NULL, 'Tank Top', 'Yellow', 'XS', 24),
(NULL, 'Polo Shirt', 'Black', 'XL', 1),
(NULL, 'T-Shirt', 'Navy Blue', 'S', 28),
(NULL, 'Hoodie', 'White', 'M', 17),
(NULL, 'T-Shirt', 'Green', 'L', 3),
(NULL, 'Sweatshirt', 'Yellow', 'XXL', 32),
(NULL, 'Tank Top', 'Black', 'XL', 6),
(NULL, 'Polo Shirt', 'Red', 'M', 20),
(NULL, 'T-Shirt', 'White', 'XS', 10),
(NULL, 'Hoodie', 'Navy Blue', 'L', 39),
(NULL, 'T-Shirt', 'Red', 'XXL', 4),
(NULL, 'Sweatshirt', 'Black', 'M', 23),
(NULL, 'Tank Top', 'Green', 'S', 12),
(NULL, 'Polo Shirt', 'White', 'XL', 28),
(NULL, 'T-Shirt', 'Yellow', 'L', 15),
(NULL, 'Hoodie', 'Red', 'M', 2),
(NULL, 'T-Shirt', 'Black', 'XS', 37),
(NULL, 'Sweatshirt', 'Navy Blue', 'XXL', 14),
(NULL, 'Tank Top', 'Yellow', 'L', 9),
(NULL, 'Polo Shirt', 'Black', 'M', 26),
(NULL, 'T-Shirt', 'Green', 'S', 5)
;
select * from tshirt_Table;
insert into tshirt_Table (article_Type, color, shirt_Size, last_Worn)
values ('Polo Shirt', 'Purple', 'M', 50);
select * from tshirt_Table where article_Type='Polo Shirt' and color='White';
select article_Type, color, shirt_Size, last_Worn from tshirt_Table;
update tshirt_Table set shirt_Size='L' where shirt_Size='M';
desc tshirt_Table;
select article_Type, color from tshirt_Table order by article_Type asc;
select * from tshirt_Table where shirt_Size = 'M' order by color asc;
select * from tshirt_table where article_Type = 'Polo Shirt';
update tshirt_Table set shirt_Size = 'M' where article_Type = 'Polo Shirt';
select * from tshirt_table where last_Worn = '35';
update tshirt_Table set color = 'Black' where last_Worn = '35';
select * from tshirt_table where last_Worn = '35';
select * from tshirt_Table where color = 'White';
update tshirt_Table set color = 'Light Blue', last_Worn = '37' where article_Type = 'Tank Top';
select * from tshirt_table where article_Type = 'Tank Top';
select * from tshirt_table where last_Worn = '35';
delete from tshirt_table where last_Worn = '35';
select * from tshirt_table;
delete from tshirt_table where last_Worn = '50';